---
name: heredoc
version: '0.1.0.0'
category: Text
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com
copyright: 2018 Patrick Brisbin
license: MIT
github: pbrisbin/heredoc
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && <5

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - text

tests:
  heredoc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - heredoc
      - hspec
      - shakespeare
